### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by stevage** [kbariotis/parcel-bootstrap-pug#1]
Freshly upgraded node and NPM on OSX.

```
$ npm run start

> parcel-bootstrap-pug@1.0.0 start /Users/steveb/dev/parcel-bootstrap-pug
> node bundler.js

Server running at http://localhost:1234
🚨  Maximum call stack size exceeded
    at md5 (/Users/steveb/dev/parcel-bootstrap-pug/node_modules/parcel-bundler/src/utils/md5.js:7:6)
    at JadeAsset.generateBundleName (/Users/steveb/dev/parcel-bootstrap-pug/node_modules/parcel-bundler/src/Asset.js:170:12)
    at Bundler.createBundleTree (/Users/steveb/dev/parcel-bootstrap-pug/node_modules/parcel-bundler/src/Bundler.js:396:46)
    at Bundler.createBundleTree (/Users/steveb/dev/parcel-bootstrap-pug/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/steveb/dev/parcel-bootstrap-pug/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/steveb/dev/parcel-bootstrap-pug/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/steveb/dev/parcel-bootstrap-pug/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/steveb/dev/parcel-bootstrap-pug/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/steveb/dev/parcel-bootstrap-pug/node_modules/parcel-bundler/src/Bundler.js:413:12)
```

**Comment by kbariotis** [comment]
Thank you @stevage. There is an open issue over for this https://github.com/parcel-bundler/parcel/issues/463. :) You don't need it though if all you need is the Pug plugin.
